### ISSUE TITLE
Link to alternative approach?

### ISSUE THREAD

**Issue by jesse-c** [balabit/ipython3-versioncontrol#4]
Hi!

First of all, thanks for creating this project. We were looking into committing our notebooks to version control and came across this. In the end we decided on a [slightly different approach (to 'clean' or 'reset' some values that aren't important to be tracked)](https://github.com/jesse-c/ipython3-versioncontrol), and I was wondering if you'd like to link to this approach from your repo? If not, no problem!

**Comment by ghostrider77** [comment]
Hi, thanks for your comment. As you might noticed, this project not under active development, to put it nicely. It was born out of need and frustration, so we have written it in a couple of afternoons and made it publicly available. No maintenance, refactoring or whatsoever has been done since its first publication. I am open to link your repository, but this might take some time, as we are quite busy with other projects. What make things a bit complicated is that the code snippets are hosted on the company's repo that I work for and not on my private repo. Anyway, I'll return to your query soon.

**Comment by jesse-c** [comment]
Oh no problem, and thank you for the reply @ghostrider77. My main motivation was that this project shows up in search results and is linked to by a blog post which also shows up high in some search results. There's no rush, and all I was thinking was a simple sentence + link in the readme, which I could create a PR to do myself if you'd like.

**Comment by ghostrider77** [comment]
Hi, your repo has been linked from the ReadMe page.

**Comment by jesse-c** [comment]
Ah great, thanks for doing that @ghostrider77 :)
